spring.application.name=bibliotecApi
spring.datasource.url=jdbc:mysql://localhost:3306/bibliotecadb
spring.datasource.username=root
spring.datasource.password=
api.security.expirationMs=${EXPIRATION_MS}
api.security.secret=${JWT_SECRET}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect